TrajectoryPlannerROS:
  max_vel_x: 0.5 # The maximum forward velocity allowed for the base in meters/sec
  min_vel_x: 0.025 # The minimum forward velocity allowed for the base in meters/sec.
  max_vel_theta: 0.9 #The maximum rotational velocity allowed for the base in radians/sec
  min_vel_theta: -0.9 #The minimum rotational velocity allowed for the base in radians/sec
  min_in_place_vel_theta: 0.5 # default 0.4 # The minimum rotational velocity allowed for the base while performing in-place rotations in radians/sec
  escape_vel: 0.05 # -0.1 # m/s, the speed used for reversing when unstucking itself

  acc_lim_theta: 0.8 #The rotational acceleration limit of the robot in radians/sec^2
  acc_lim_x: 0.35 #The x acceleration limit of the robot in meters/sec^2

  yaw_goal_tolerance: 0.1 # 0.25 # rotational tolerance of the controller in radians when achieving its goal
  xy_goal_tolerance: 0.075 # the translational tolerance of the controller in meters when achieving its goal

  latch_xy_goal_tolerance: true
  meter_scoring: true #Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells.
  path_distance_bias: 2.0 # 0.6 # The weighting for how much the controller should stay close to the path it was given, maximal possible value is 5.0
  goal_distance_bias: 0.6 # 0.8 # The weighting for how much the controller should attempt to reach its local goal, also controls speed, maximal possible value is 5.0
  occdist_scale: 0.01 # 0.01 # how much the controller should attempt to avoid obstacles 

  sim_granularity: 0.05 # the map is this size
  angular_sim_granularity: 0.047 

  heading_scoring: false
  heading_scoring_timestep: 1

  dwa: false
  use_dwa: false
  holonomic_robot: false #Determines whether velocity commands are generated for a holonomic or non-holonomic robot.
