obstacle_range: 3.0 #The maximum range in meters at which to insert obstacles into the costmap using sensor data. # If less then this value, it is an obstacle
raytrace_range: 5.0 #The maximum range in meters at which to raytrace out obstacles from the map using sensor data. # maintain this value away from obstacle

#The footprint of the robot specified in the robot_base_frame coordinate frame as a list in the format: [ [x1, y1], [x2, y2], ...., [xn, yn] ]. The footprint specification assumes the center point of the robot is at (0.0, 0.0)
footprint: [[0.20, 0.2], [0.20,-0.2], [-0.25,-0.2], [-0.25,-0.075], [-0.45,-0.075], [-0.45,0.075], [-0.25,0.075], [-0.25,0.2]]
inflation_layer:
  inflation_radius: 0.5 # m # Original is 0.55m
  cost_scaling_factor: 10.0 #10.0

max_obstacle_height: 2.0 # m
min_obstacle_height: 0.0 # m

#observation_source: A list of observation source names separated by spaces
#	/sensor_frame: The frame of the origin of the sensor
#	/topic		 : The topic on which sensor data comes in for this source.
#	data_type    : The data type associated with the topic.
#	clearing     : Whether or not this observation should be used to clear out freespace
#	marking      : Whether or not this observation should be used to mark obstacles.

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: podi_laser_scanner, data_type: LaserScan, topic: podi/laser, marking: true, clearing: true}

#More information at http://wiki.ros.org/costmap_2d and http://wiki.ros.org/costmap_2d/flat
