# --- These are paremeters that would be searched for by the code. It doesn't need to be at the correct level. ---

#The footprint of the robot specified in the robot_base_frame coordinate frame as a list in the format: [ [x1, y1], [x2, y2], ...., [xn, yn] ]. The footprint specification assumes the center point of the robot is at (0.0, 0.0)
# footprint: [[0.20, 0.2], [0.20,-0.2], [-0.25,-0.2], [-0.25,-0.075], [-0.45,-0.075], [-0.45,0.075], [-0.25,0.075], [-0.25,0.2]]
footprint: [[0.20, 0.2], [0.20,-0.2], [-0.3,-0.2], [-0.3,0.2]]

# --- These parameters are copied over from the parent level and do not needed to be included in their own level. ---

# For costmap_2d::ObstacleLayer
obstacle_range: 3.0 #The maximum range in meters at which to insert obstacles into the costmap using sensor data. # If less then this value, it is an obstacle
raytrace_range: 5.0 #The maximum range in meters at which to raytrace out obstacles from the map using sensor data. # maintain this value away from obstacle

# For costmap_2d::InflationLayer
inflation_radius: 0.5 # default (0.55) # In meters
cost_scaling_factor: 40 # default (10.0)


# --- These parameters are set to their correct level

# costmap_2d::ObstacleLayer

#observation_source: A list of observation source names separated by spaces
# sensor_frame : The frame of the origin of the sensor
# topic		     : The topic on which sensor data comes in for this source.
# data_type    : The data type associated with the topic.
# clearing     : Whether or not this observation should be used to clear out freespace
# marking      : Whether or not this observation should be used to mark obstacles.

obstacle_layer:
  transform_tolerance: 0.3 # 0.3 is the default
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: podi_laser_scanner, 
    data_type: LaserScan, 
    topic: /podi/laser, 
    marking: true, 
    clearing: true,
    expected_update_rate: 10,
    observation_keep_time: 0.2
  }

# tbd_costmap::HumanLayer

human_layer:
  ignore_time_stamp: false
  inflation: 0.4


# tbd_costmap::InteractionSpaceLayer

interaction_space_layer:
  ignore_time_stamp: false
