global_costmap:
  global_frame: podi_map
  robot_base_frame: podi_base_link
  update_frequency: 5.0
  publish_frequency: 2.5
  static_map: true
  map_type: voxel # What map type to use. "voxel" or "costmap" are the supported types, with the difference between them being a 3D-view of the world vs. a 2D-view of the world.
  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: human_layer, type: "tbd_costmap::HumanLayer" }
    - { name: interaction_space_layer, type: "tbd_costmap::InteractionSpaceLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
