local_costmap:
  global_frame: podi_odom
  robot_base_frame: podi_base_link
  update_frequency: 5.0 #The frequency in Hz for the map to be updated.
  publish_frequency: 2.5 #The frequency in Hz for the map to be publish display information.
  width: 5.0 #The width of the map in meters.
  height: 5.0 #The height of the map in meters.

  static_map: false #Whether or not to use the static map to initialize the costmap
  rolling_window: true #Whether or not to use a rolling window version of the costmap.
  resolution: 0.05 #The resolution of the map in meters/cell.
  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }