SBPLLatticePlanner:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 3.0
  initial_epsilon: 3.0
  forward_search: false
  nominalvel_mpersecs: 1
  timetoturn45degsinplace_secs: 2.6
  primitive_filename: "$(find tbd_podi_2dnav)/config/prim_right_angles.mprim"
  lethal_obstacle: 20
  number_thetas: 4
  