# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        ros_distributions: 
          - melodic
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup ROS environment
      - uses: ros-tooling/setup-ros@0.0.20
        with: 
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - run: "source /opt/ros/${{ matrix.ros_distribution }}/setup.bash && rosnode --help"  
